from django.db import models

class DadosPessoa(models.Model):
    name = models.TextField()
    tel = models.TextField()
    mail = models.TextField()
    birth = models.TextField()
    prof = models.TextField()
    github = models.TextField()
    idioma1 = models.TextField()
    idioma2 = models.TextField()
    idioma3 = models.TextField()
    tech1 = models.TextField()
    tech2 = models.TextField()
    tech3 = models.TextField()
    tech4 = models.TextField()
    tech5 = models.TextField()
    tech6 = models.TextField()
    tech7 = models.TextField()
    tech8 = models.TextField()
    tech9 = models.TextField()
    tech10 = models.TextField()
    tech11 = models.TextField()
    title1 = models.TextField()
    title2 = models.TextField()
    title3 = models.TextField()
    title4 = models.TextField()
    title5 = models.TextField()
    title6 = models.TextField()
    body1 = models.TextField()
    body2 = models.TextField()
    body3 = models.TextField()
    body4 = models.TextField()
    body5 = models.TextField()
    body6 = models.TextField()

    def __str__(self):
        return self.name