# Generated by Django 4.0.3 on 2022-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tel', models.TextField()),
                ('mail', models.TextField()),
                ('birth', models.TextField()),
            ],
        ),
    ]
