# Generated by Django 3.2.10 on 2022-04-04 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoa',
            name='prof',
            field=models.TextField(default=datetime.datetime(2022, 4, 4, 20, 29, 31, 343541, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
