# Generated by Django 3.2.10 on 2022-04-05 14:10

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_dadospessoa_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoa',
            name='body1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='body2',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 8, 35, 817356, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='body3',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 8, 41, 161695, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='body4',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='body5',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 8, 53, 58686, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='body6',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='github',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 19, 638153, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='idioma1',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 23, 904104, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='idioma2',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 25, 890025, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='idioma3',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 34, 435882, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech1',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 37, 957482, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech10',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 41, 114494, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech11',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 42, 446841, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech2',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 43, 800366, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech3',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 46, 516232, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech4',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 48, 470004, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech5',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 50, 57234, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech6',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 55, 963738, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech7',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 57, 686796, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech8',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 9, 59, 98800, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='tech9',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 10, 0, 835161, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='title1',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 10, 3, 391827, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='title2',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 10, 5, 33116, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='title3',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 10, 7, 28545, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='title4',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 10, 8, 676103, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='title5',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 10, 10, 694985, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoa',
            name='title6',
            field=models.TextField(default=datetime.datetime(2022, 4, 5, 14, 10, 12, 578486, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
